# Generated by Django 5.2.6 on 2025-10-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAndReg', '0003_animeactivity_automationalert_cryptoactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facebook_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
